version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: smart-leads-db
    restart: always
    environment:
      MYSQL_DATABASE: smart_leads_db
      MYSQL_ROOT_PASSWORD: Admin@123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: smart-leads-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/smart_leads_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Admin@123
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: smart-leads-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
